resolver: nightly-2020-06-25

packages:
  - .
  - ../numhask
  - ../numhask-space
  - ../chart-svg

extra-deps:
  - graphviz-2999.20.1.0
  - reanimate-1.1.1.0
  - reanimate-svg-0.13.0.0
  - hgeometry-0.11.0.0
  - hgeometry-combinatorial-0.11.0.0
  - vinyl-0.13.0
